# application-develop.yml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/schedule?&characterEncoding=UTF-8&serverTimeZone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: hwi-schedule

# NoHandlerFoundException을 위해 추가한 설정
  web:
    resources:
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  sql:
    init:
      mode: always

logging:
  level:
    org.hibernate.SQL: debug
