# application-develop.yml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/schedule?&characterEncoding=UTF-8&serverTimeZone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: hwi-schedule

# NoHandlerFoundException을 위해 추가한 설정
  web:
    resources:
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  sql:
    init:
      mode: always

  redis:
    host: localhost
    port: 6379

oauth2:
  google:
    client-id: 1029084464788-djecku9p399gj4jnk1ie9iolm55cq1kk.apps.googleusercontent.com
    authentication-url: https://accounts.google.com/o/oauth2/auth
    response-type: code
    token-url: https://oauth2.googleapis.com/token
    grant-type: authorization_code
    redirect-uri: http://localhost:3000/oauth2/GOOGLE/callback
    scopes: openid, email, profile

jwt:
  secret-key: dev:wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww
  access-token-expiry: 10000
  refresh-token-expiry: 10000
  issuer: me

logging:
  level:
    org.hibernate.SQL: debug
