name: Java CD with GCP

on:
  push:
    branches:
      - develop
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: 'Login to gcloud'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: 'Create Schedule Instance'
      run: |
        gcloud compute instances create schedule \
          --zone=asia-northeast3 \
          --machine-type=e2-micro \
          --container-image=docker.io/khc3796/schedule:latest \
          --image=debian-12 \
          --tags=http-server,https-server \
          --network-interface=network=schedule-vpc,subnet=schedule-subnet
