name: Java CD with GCP

on:
  push:
    branches:
      - develop
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: 'actions/checkout@v4'

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Set up MySQL and Redis
      run: |
        cd docker
        docker-compose -f docker-compose-local.yml up -d

    - name: Build with Gradle
      run: |
        echo ${{ secrets.APPLICATION_SECRET }} | base64 --decode > ./src/main/resources/application-secret.yml
        echo ${{ secrets.APPLICATION_PROD }} | base64 --decode > ./src/main/resources/application-prod.yml
        ./gradlew clean build

    - name: Temporarily save build artifact
      uses: actions/upload-artifact@v2
      with:
        name: build-artifact
        path: build/*
        retention-days: 1
    
    - name: 'Login to gcloud'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: Tag Docker image
      run: |
        docker build -t ${{ secrets.ARTIFACT_REGISTRY_NAME }}:$GITHUB_SHA .
        docker tag ${{ secrets.ARTIFACT_REGISTRY_NAME }}:$GITHUB_SHA ${{ secrets.ARTIFACT_REGISTRY_NAME }}:latest
          
    - name: Push Docker image to GCR
      run: |
        gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://asia-northeast3-docker.pkg.dev
        docker push ${{ secrets.ARTIFACT_REGISTRY_NAME }}:$GITHUB_SHA
        docker push ${{ secrets.ARTIFACT_REGISTRY_NAME }}:latest
      
    - name: 'Create Schedule Instance'
      run: |
        gcloud compute instances create-with-container schedule \
          --zone=asia-northeast3-a \
          --machine-type=e2-micro \
          --container-image=${{ secrets.ARTIFACT_REGISTRY_NAME }}:latest \
          --container-env=profile=prod \
          --tags=http-server,https-server,schedule-firewall \
          --network=schedule-vpc \
          --subnet=schedule-subnet \
          --boot-disk-size=10GB
          
