name: Java CD with GCP

on:
  push:
    branches:
      - develop
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: 'Login to gcloud'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    - run: gcloud auth configure-docker
    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Pull Docker image
      run: docker pull khc3796/schedule:latest

    - name: Tag Docker image
      run: docker tag khc3796/schedule:latest asia-northeast3-docker.pkg.dev/scheduleoauth2/schedule/app:latest

    # - name: Push Docker image to GCR
    #   run: docker push asia-northeast3-docker.pkg.dev/scheduleoauth2/schedule/app:latest
      
    - name: 'Create Schedule Instance'
      run: |
        gcloud compute instances create schedule \
          --zone=asia-northeast3-a \
          --machine-type=e2-micro \
          # --container-image=asia-northeast3-docker.pkg.dev/scheduleoauth2/schedule/app:latest \
          --image=Debian GNU/Linux 12 \
          --tags=http-server,https-server \
          --network=schedule-vpc \
          --subnet=schedule-subnet
