name: Java CI with Gradle

on:
  push:
    branches:
      - develop
  workflow_dispatch:

defaults:
  run:
    working-directory: ./_schedule/schedule

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Set up MySQL and Redis
        run: |
          cd docker
          docker-compose -f docker-compose-local.yml up -d

      - name: Build with Gradle
        run: |
          ./gradlew clean build

      - name: Temporarily save build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: build/*
          retention-days: 1
