name: Java CI with Gradle

on:
  push:
    branches:
      - develop
  workflow_dispatch:

defaults:
  run:
    working-directory: ./_schedule/schedule

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Set up MySql and Redis
        run: |
          cd docker
          docker-compose -f docker-compose-local.yml up -d

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Temporarily save build artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: build/*
          retention-days: 1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build Docker
        run: |
          docker build -t ${{ secrets.DOCKER_REGISTRY_NAME }}:$GITHUB_SHA .
          docker tag ${{ secrets.DOCKER_REGISTRY_NAME }}:$GITHUB_SHA ${{ secrets.DOCKER_REGISTRY_NAME }}:latest

      - name: Push Docker
        run: docker push ${{ secrets.DOCKER_REGISTRY_NAME }}:latest
